model:
  base_learning_rate: 4.5e-06
  target: transformer.cond_transformer.Net2NetTransformer
  params:
    cond_stage_key: coord
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024
        block_size: 512
        n_layer: 24
        n_head: 16
        n_embd: 1024
        embd_pdrop: 0.1
        resid_pdrop: 0.1
        attn_pdrop: 0.1
    first_stage_config:
      target: vqgan.model.vqgan.VQModel
      params:
        ckpt_path: logs/2025-08-26T02-02-37_autoencoder_FLIm/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config:
      target: taming.modules.misc.coord.CoordStage
      params:
        n_embed: 1024
        down_factor: 16

data:
  target: biggan_datasets.data_utils.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: False
    num_workers: 4
    train:
      target: biggan_datasets.surgical_tool_dataset.SurgicalToolDataset
      params:
        root_dir: "/home/ataffe/SyntheticData/SyntheticDataGenForFLImViz/data/surgvu-mesad-train"
        size: 256
    validation:
      target: biggan_datasets.surgical_tool_dataset.SurgicalToolDataset
      params:
        root_dir: "/home/ataffe/SyntheticData/SyntheticDataGenForFLImViz/data/surgvu-mesad-validation"
        size: 256

lightning:
  callbacks:
    image_logger:
      target: loggers.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: True
