model:
  base_learning_rate: 4.5e-06
  target: transformer.nano_transformer.Net2NetTransformer
  monitor: val/loss
  params:
    cond_stage_key: coord
    transformer_config:
      target: transformer.nanoGPT.nanogpt.NanoGPT
      params:
        config:
          sequence_len: 512 # = Block size in minGPT
          vocab_size: 2048
          n_layer: 24
          n_head: 16
          n_kv_head: 16
          n_embd: 2048
          window_pattern: SSSL
    first_stage_config:
      target: vqgan.model.vqgan.VQModel
      params:
        ckpt_path: /mnt/bddd2eea-89b7-45b0-8345-df09af140cd6/research/surgical-tool-gen/Checkpoints/vqgan/2026-02-18T14-09-24_vqgan_flim_488nm_fine_tuning/vqgan_checkpoint.ckpt
        embed_dim: 256
        n_embed: 2048
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config:
      target: taming.modules.misc.coord.CoordStage
      params:
        n_embed: 1024
        down_factor: 16

data:
  target: datasets.data_utils.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: False
    num_workers: 8
    train:
      target: datasets.surgical_tool_dataset.SurgicalToolDataset
      params:
        root_dir: "/home/ataffe/SyntheticData/SyntheticDataGenForFLImViz/data/FLIm-488nm/train"
        size: 256
    validation:
      target: datasets.surgical_tool_dataset.SurgicalToolDataset
      params:
        root_dir: "/home/ataffe/SyntheticData/SyntheticDataGenForFLImViz/data/FLIm-488nm/val"
        size: 256

lightning:
  callbacks:
    image_logger:
      target: loggers.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: True

trainer:
    benchmark: True
    accelerator: cuda
    devices: auto
